rect#id(pos=[12,12],size=[16,12])
    ht#abbb(size=[8,8])
bruh#b()
        .group1.group2()
        #id2()
    idoubtthiswillwork.yesitwill()
    a()
wait#did.i(just=make,an=actual,language=myself??)